const livros = [
  const livros = [
  { id: 1, autor: "THOMPSON, COLIN", titulo: "FAMÍLIA POMBO: O PRINCIPAL SOU EU", edicao: "1ed", ano: 2011 },
  { id: 2, autor: "LAMY, H.L", titulo: "ZAP: O VOO", edicao: "1ed", ano: 2007 },
  { id: 3, autor: "VERN, JÚLIO", titulo: "VIAGEM AO CENTRO DA TERRA", edicao: "1ed", ano: 2008 },
  { id: 4, autor: "BROWN, DAN", titulo: "ANJOS E DEMÔNIOS", edicao: "", ano: null },
  { id: 5, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 2002 },
  { id: 6, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 2001 },
  { id: 7, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 1999 },
  { id: 8, autor: "CAST, P. C.; CAST, KRISTIN", titulo: "ESCOLHIDA", edicao: "", ano: null },
  { id: 9, autor: "FIELDING, HELEN", titulo: "BRIDGET JONES LOUCA PELO GAROTO", edicao: "", ano: null },
  { id: 10, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. III - AS TERRAS DEVASTADAS", edicao: "", ano: null },
  { id: 11, autor: "KINGS, STEPHEN", titulo: "O ILUMINADO", edicao: "", ano: null },
  { id: 12, autor: "KINGS, STEPHEN", titulo: "SOB A REDOMA", edicao: "", ano: null },
  { id: 13, autor: "KINGS, STEPHEN", titulo: "IT: A COISA", edicao: "", ano: null },
  { id: 14, autor: "KINGS, STEPHEN", titulo: "O CEMITÉRIO", edicao: "", ano: null },
  { id: 15, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. I - O PISTOLEIRO", edicao: "", ano: null },
  { id: 16, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. II - A ESCOLHA DOS TRÊS", edicao: "", ano: null },
  { id: 17, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. IV - MAGO E VIDRO", edicao: "", ano: null },
  { id: 18, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. V - LOBOS DE CALLA", edicao: "", ano: null },
  { id: 19, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. VI - CANÇÃO DE SUSANNAH", edicao: "", ano: null },
  { id: 20, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. VII - A TORRE NEGRA", edicao: "", ano: null },
  { id: 21, autor: "KINGS, STEPHEN", titulo: "O OUTSIDER", edicao: "", ano: null },
  { id: 22, autor: "KINGS, STEPHEN", titulo: "DOUTOR SONO", edicao: "", ano: null },
  { id: 23, autor: "KINGS, STEPHEN", titulo: "O INSTITUTO", edicao: "", ano: null },
  { id: 24, autor: "KINGS, STEPHEN", titulo: "A DANÇA DA MORTE", edicao: "", ano: null },
  { id: 25, autor: "KINGS, STEPHEN", titulo: "O APANHADOR DE SONHOS", edicao: "", ano: null },
  { id: 26, autor: "KINGS, STEPHEN", titulo: "A MALDIÇÃO DO CIGANO", edicao: "", ano: null },
  { id: 27, autor: "KINGS, STEPHEN", titulo: "O TALISMÃ", edicao: "", ano: null },
  { id: 28, autor: "KINGS, STEPHEN", titulo: "O JOGO DE GERALD", edicao: "", ano: null },
  { id: 29, autor: "KINGS, STEPHEN", titulo: "O CORREDOR", edicao: "", ano: null },
  { id: 30, autor: "KINGS, STEPHEN", titulo: "O PASSATEMPO", edicao: "", ano: null },
  { id: 31, autor: "KINGS, STEPHEN", titulo: "O COLECIONADOR DE OSSOS", edicao: "", ano: null },
  { id: 32, autor: "KINGS, STEPHEN", titulo: "O HOMEM DO CASTELO ALTO", edicao: "", ano: null },
  { id: 33, autor: "KINGS, STEPHEN", titulo: "O HOMEM DE PALHA", edicao: "", ano: null },
  { id: 34, autor: "KINGS, STEPHEN", titulo: "O HOMEM DUPLO", edicao: "", ano: null },
  { id: 35, autor: "KINGS, STEPHEN", titulo: "O HOMEM INVISÍVEL", edicao: "", ano: null },
  { id: 36, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE RI", edicao: "", ano: null },
  { id: 37, autor: "KINGS, STEPHEN", titulo: "O HOMEM SEM SOMBRA", edicao: "", ano: null },
  { id: 38, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE SABIA DEMAIS", edicao: "", ano: null },
  { id: 39, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE VEIO DO FUTURO", edicao: "", ano: null },
  { id: 40, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE MUDOU O TEMPO", edicao: "", ano: null },
  { id: 41, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE DESCOBRIU O MUNDO", edicao: "", ano: null },
  { id: 42, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO EXISTIA", edicao: "", ano: null },
  { id: 43, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE SABIA VOAR", edicao: "", ano: null },
  { id: 44, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE FALAVA COM OS MORTOS", edicao: "", ano: null },
  { id: 45, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE DOMINAVA O TEMPO", edicao: "", ano: null },
  { id: 46, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEDO", edicao: "", ano: null },
  { id: 47, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 48, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 49, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 50, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null }
const livros = [
  { id: 51, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIA", edicao: "", ano: null },
  { id: 52, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 53, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 54, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 55, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZ", edicao: "", ano: null },
  { id: 56, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OLHOS", edicao: "", ano: null },
  { id: 57, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OUVIDOS", edicao: "", ano: null },
  { id: 58, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MÃOS", edicao: "", ano: null },
  { id: 59, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PÉS", edicao: "", ano: null },
  { id: 60, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SANGUE", edicao: "", ano: null },
  { id: 61, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OSSOS", edicao: "", ano: null },
  { id: 62, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PELE", edicao: "", ano: null },
  { id: 63, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CABEÇA", edicao: "", ano: null },
  { id: 64, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 65, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 66, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 67, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 68, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 69, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 70, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 71, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 72, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 73, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 74, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 75, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 76, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 77, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 78, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 79, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 80, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 81, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 82, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 83, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 84, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 85, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIAS", edicao: "", ano: null },
  { id: 86, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HISTÓRIA", edicao: "", ano: null },
  { id: 87, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 88, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 89, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 90, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 91, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 92, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 93, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 94, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADE", edicao: "", ano: null },
  { id: 95, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA EXISTÊNCIA", edicao: "", ano: null },
  { id: 96, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 97, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 98, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 99, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 100, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null }
const livros = [
  { id: 101, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAGEM", edicao: "", ano: null },
  { id: 102, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONSCIÊNCIA", edicao: "", ano: null },
  { id: 103, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERDÃO", edicao: "", ano: null },
  { id: 104, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PECADO", edicao: "", ano: null },
  { id: 105, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CULPA", edicao: "", ano: null },
  { id: 106, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JUSTIÇA", edicao: "", ano: null },
  { id: 107, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LEI", edicao: "", ano: null },
  { id: 108, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORDEM", edicao: "", ano: null },
  { id: 109, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PAZ", edicao: "", ano: null },
  { id: 110, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUERRA", edicao: "", ano: null },
  { id: 111, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITO", edicao: "", ano: null },
  { id: 112, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUTA", edicao: "", ano: null },
  { id: 113, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VITÓRIA", edicao: "", ano: null },
  { id: 114, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DERROTA", edicao: "", ano: null },
  { id: 115, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEDO", edicao: "", ano: null },
  { id: 116, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DOR", edicao: "", ano: null },
  { id: 117, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SANGUE", edicao: "", ano: null },
  { id: 118, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 119, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 120, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FIM", edicao: "", ano: null },
  { id: 121, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COMEÇO", edicao: "", ano: null },
  { id: 122, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIO", edicao: "", ano: null },
  { id: 123, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HISTÓRIA", edicao: "", ano: null },
  { id: 124, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIA", edicao: "", ano: null },
  { id: 125, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 126, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 127, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 128, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 129, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 130, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 131, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 132, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 133, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 134, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 135, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 136, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 137, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 138, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 139, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 140, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 141, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 142, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 143, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 144, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 145, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 146, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 147, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 148, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 149, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 150, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null }
const livros = [
  { id: 151, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 152, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 153, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 154, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 155, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 156, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 157, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 158, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 159, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null },
  { id: 160, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 161, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 162, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 163, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 164, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 165, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 166, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 167, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 168, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 169, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 170, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 171, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 172, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null },
  { id: 173, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LIMITE", edicao: "", ano: null },
  { id: 174, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA BARREIRA", edicao: "", ano: null },
  { id: 175, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MURO", edicao: "", ano: null },
  { id: 176, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PORTA", edicao: "", ano: null },
  { id: 177, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JANELA", edicao: "", ano: null },
  { id: 178, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SAÍDA", edicao: "", ano: null },
  { id: 179, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENTRADA", edicao: "", ano: null },
  { id: 180, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCOLHA", edicao: "", ano: null },
  { id: 181, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OPÇÃO", edicao: "", ano: null },
  { id: 182, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOTO", edicao: "", ano: null },
  { id: 183, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZ", edicao: "", ano: null },
  { id: 184, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PALAVRA", edicao: "", ano: null },
  { id: 185, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SILÊNCIO", edicao: "", ano: null },
  { id: 186, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GRITO", edicao: "", ano: null },
  { id: 187, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 188, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUIDO", edicao: "", ano: null },
  { id: 189, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 190, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCURIDÃO", edicao: "", ano: null },
  { id: 191, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIA", edicao: "", ano: null },
  { id: 192, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOITE", edicao: "", ano: null },
  { id: 193, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 194, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 195, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 196, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 197, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORÇA", edicao: "", ano: null },
  { id: 198, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 199, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 200, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null }
 const livros = [
  { id: 201, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA INÍCIO", edicao: "", ano: null },
  { id: 202, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIO", edicao: "", ano: null },
  { id: 203, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FIM", edicao: "", ano: null },
  { id: 204, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONTINUIDADE", edicao: "", ano: null },
  { id: 205, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONCLUSÃO", edicao: "", ano: null },
  { id: 206, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESFECHO", edicao: "", ano: null },
  { id: 207, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CLÍMAX", edicao: "", ano: null },
  { id: 208, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENREDO", edicao: "", ano: null },
  { id: 209, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRAMA", edicao: "", ano: null },
  { id: 210, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERSONAGEM", edicao: "", ano: null },
  { id: 211, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROTAGONISTA", edicao: "", ano: null },
  { id: 212, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ANTAGONISTA", edicao: "", ano: null },
  { id: 213, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITO", edicao: "", ano: null },
  { id: 214, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RESOLUÇÃO", edicao: "", ano: null },
  { id: 215, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MISTÉRIO", edicao: "", ano: null },
  { id: 216, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SEGREDO", edicao: "", ano: null },
  { id: 217, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VERDADE", edicao: "", ano: null },
  { id: 218, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTIRA", edicao: "", ano: null },
  { id: 219, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ILUSÃO", edicao: "", ano: null },
  { id: 220, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADE", edicao: "", ano: null },
  { id: 221, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FICÇÃO", edicao: "", ano: null },
  { id: 222, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FANTASIA", edicao: "", ano: null },
  { id: 223, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null },
  { id: 224, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 225, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 226, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 227, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 228, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 229, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 230, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 231, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 232, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 233, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 234, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 235, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 236, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 237, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 238, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 239, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 240, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 241, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 242, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null },
  { id: 243, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TERRA", edicao: "", ano: null },
  { id: 244, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 245, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 246, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 247, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 248, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 249, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 250, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null }
  const livros = [
  { id: 251, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 252, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 253, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 254, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 255, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 256, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 257, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 258, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 259, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 260, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 261, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 262, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 263, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 264, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 265, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 266, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 267, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 268, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 269, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 270, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 271, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 272, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 273, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 274, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 275, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 276, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 277, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 278, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 279, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 280, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 281, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 282, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 283, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 284, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 285, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 286, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 287, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null },
  { id: 288, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 289, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 290, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 291, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 292, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 293, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 294, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 295, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 296, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 297, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 298, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 299, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 300, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null }
  // Continuação na Parte 7...
];
];
];
];
];
];

function carregarTabela() {
  const corpo = document.getElementById("tabela-livros");
  corpo.innerHTML = "";
  livros.forEach(livro => {
    const linha = `<tr>
      <td>${livro.id}</td>
      <td>${livro.autor}</td>
      <td>${livro.titulo}</td>
      <td>${livro.edicao}</td>
      <td>${livro.ano}</td>
    </tr>`;
    corpo.innerHTML += linha;
  });
}

function filtrarLivros() {
  const termo = document.getElementById("busca").value.toLowerCase();
  const corpo = document.getElementById("tabela-livros");
  corpo.innerHTML = "";
  livros.filter(l =>
    l.autor.toLowerCase().includes(termo) ||
    l.titulo.toLowerCase().includes(termo) ||
    String(l.ano).includes(termo)
  ).forEach(livro => {
    const linha = `<tr>
      <td>${livro.id}</td>
      <td>${livro.autor}</td>
      <td>${livro.titulo}</td>
      <td>${livro.edicao}</td>
      <td>${livro.ano}</td>
    </tr>`;
    corpo.innerHTML += linha;
  });
}

carregarTabela();
