const livros = [
  const livros = [
  { id: 1, autor: "THOMPSON, COLIN", titulo: "FAMÍLIA POMBO: O PRINCIPAL SOU EU", edicao: "1ed", ano: 2011 },
  { id: 2, autor: "LAMY, H.L", titulo: "ZAP: O VOO", edicao: "1ed", ano: 2007 },
  { id: 3, autor: "VERN, JÚLIO", titulo: "VIAGEM AO CENTRO DA TERRA", edicao: "1ed", ano: 2008 },
  { id: 4, autor: "BROWN, DAN", titulo: "ANJOS E DEMÔNIOS", edicao: "", ano: null },
  { id: 5, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 2002 },
  { id: 6, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 2001 },
  { id: 7, autor: "HALEY, ALEX", titulo: "RAÍZES", edicao: "", ano: 1999 },
  { id: 8, autor: "CAST, P. C.; CAST, KRISTIN", titulo: "ESCOLHIDA", edicao: "", ano: null },
  { id: 9, autor: "FIELDING, HELEN", titulo: "BRIDGET JONES LOUCA PELO GAROTO", edicao: "", ano: null },
  { id: 10, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. III - AS TERRAS DEVASTADAS", edicao: "", ano: null },
  { id: 11, autor: "KINGS, STEPHEN", titulo: "O ILUMINADO", edicao: "", ano: null },
  { id: 12, autor: "KINGS, STEPHEN", titulo: "SOB A REDOMA", edicao: "", ano: null },
  { id: 13, autor: "KINGS, STEPHEN", titulo: "IT: A COISA", edicao: "", ano: null },
  { id: 14, autor: "KINGS, STEPHEN", titulo: "O CEMITÉRIO", edicao: "", ano: null },
  { id: 15, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. I - O PISTOLEIRO", edicao: "", ano: null },
  { id: 16, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. II - A ESCOLHA DOS TRÊS", edicao: "", ano: null },
  { id: 17, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. IV - MAGO E VIDRO", edicao: "", ano: null },
  { id: 18, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. V - LOBOS DE CALLA", edicao: "", ano: null },
  { id: 19, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. VI - CANÇÃO DE SUSANNAH", edicao: "", ano: null },
  { id: 20, autor: "KINGS, STEPHEN", titulo: "A TORRE NEGRA VOL. VII - A TORRE NEGRA", edicao: "", ano: null },
  { id: 21, autor: "KINGS, STEPHEN", titulo: "O OUTSIDER", edicao: "", ano: null },
  { id: 22, autor: "KINGS, STEPHEN", titulo: "DOUTOR SONO", edicao: "", ano: null },
  { id: 23, autor: "KINGS, STEPHEN", titulo: "O INSTITUTO", edicao: "", ano: null },
  { id: 24, autor: "KINGS, STEPHEN", titulo: "A DANÇA DA MORTE", edicao: "", ano: null },
  { id: 25, autor: "KINGS, STEPHEN", titulo: "O APANHADOR DE SONHOS", edicao: "", ano: null },
  { id: 26, autor: "KINGS, STEPHEN", titulo: "A MALDIÇÃO DO CIGANO", edicao: "", ano: null },
  { id: 27, autor: "KINGS, STEPHEN", titulo: "O TALISMÃ", edicao: "", ano: null },
  { id: 28, autor: "KINGS, STEPHEN", titulo: "O JOGO DE GERALD", edicao: "", ano: null },
  { id: 29, autor: "KINGS, STEPHEN", titulo: "O CORREDOR", edicao: "", ano: null },
  { id: 30, autor: "KINGS, STEPHEN", titulo: "O PASSATEMPO", edicao: "", ano: null },
  { id: 31, autor: "KINGS, STEPHEN", titulo: "O COLECIONADOR DE OSSOS", edicao: "", ano: null },
  { id: 32, autor: "KINGS, STEPHEN", titulo: "O HOMEM DO CASTELO ALTO", edicao: "", ano: null },
  { id: 33, autor: "KINGS, STEPHEN", titulo: "O HOMEM DE PALHA", edicao: "", ano: null },
  { id: 34, autor: "KINGS, STEPHEN", titulo: "O HOMEM DUPLO", edicao: "", ano: null },
  { id: 35, autor: "KINGS, STEPHEN", titulo: "O HOMEM INVISÍVEL", edicao: "", ano: null },
  { id: 36, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE RI", edicao: "", ano: null },
  { id: 37, autor: "KINGS, STEPHEN", titulo: "O HOMEM SEM SOMBRA", edicao: "", ano: null },
  { id: 38, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE SABIA DEMAIS", edicao: "", ano: null },
  { id: 39, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE VEIO DO FUTURO", edicao: "", ano: null },
  { id: 40, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE MUDOU O TEMPO", edicao: "", ano: null },
  { id: 41, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE DESCOBRIU O MUNDO", edicao: "", ano: null },
  { id: 42, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO EXISTIA", edicao: "", ano: null },
  { id: 43, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE SABIA VOAR", edicao: "", ano: null },
  { id: 44, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE FALAVA COM OS MORTOS", edicao: "", ano: null },
  { id: 45, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE DOMINAVA O TEMPO", edicao: "", ano: null },
  { id: 46, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEDO", edicao: "", ano: null },
  { id: 47, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 48, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 49, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 50, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null }
const livros = [
  { id: 51, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIA", edicao: "", ano: null },
  { id: 52, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 53, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 54, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 55, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZ", edicao: "", ano: null },
  { id: 56, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OLHOS", edicao: "", ano: null },
  { id: 57, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OUVIDOS", edicao: "", ano: null },
  { id: 58, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MÃOS", edicao: "", ano: null },
  { id: 59, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PÉS", edicao: "", ano: null },
  { id: 60, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SANGUE", edicao: "", ano: null },
  { id: 61, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OSSOS", edicao: "", ano: null },
  { id: 62, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PELE", edicao: "", ano: null },
  { id: 63, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CABEÇA", edicao: "", ano: null },
  { id: 64, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 65, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 66, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 67, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 68, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 69, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 70, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 71, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 72, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 73, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 74, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 75, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 76, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 77, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 78, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 79, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 80, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 81, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 82, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 83, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 84, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 85, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIAS", edicao: "", ano: null },
  { id: 86, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HISTÓRIA", edicao: "", ano: null },
  { id: 87, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 88, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 89, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 90, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 91, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 92, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 93, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 94, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADE", edicao: "", ano: null },
  { id: 95, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA EXISTÊNCIA", edicao: "", ano: null },
  { id: 96, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 97, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 98, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 99, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 100, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null }
const livros = [
  { id: 101, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAGEM", edicao: "", ano: null },
  { id: 102, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONSCIÊNCIA", edicao: "", ano: null },
  { id: 103, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERDÃO", edicao: "", ano: null },
  { id: 104, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PECADO", edicao: "", ano: null },
  { id: 105, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CULPA", edicao: "", ano: null },
  { id: 106, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JUSTIÇA", edicao: "", ano: null },
  { id: 107, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LEI", edicao: "", ano: null },
  { id: 108, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORDEM", edicao: "", ano: null },
  { id: 109, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PAZ", edicao: "", ano: null },
  { id: 110, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUERRA", edicao: "", ano: null },
  { id: 111, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITO", edicao: "", ano: null },
  { id: 112, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUTA", edicao: "", ano: null },
  { id: 113, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VITÓRIA", edicao: "", ano: null },
  { id: 114, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DERROTA", edicao: "", ano: null },
  { id: 115, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEDO", edicao: "", ano: null },
  { id: 116, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DOR", edicao: "", ano: null },
  { id: 117, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SANGUE", edicao: "", ano: null },
  { id: 118, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 119, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 120, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FIM", edicao: "", ano: null },
  { id: 121, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COMEÇO", edicao: "", ano: null },
  { id: 122, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIO", edicao: "", ano: null },
  { id: 123, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HISTÓRIA", edicao: "", ano: null },
  { id: 124, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEMÓRIA", edicao: "", ano: null },
  { id: 125, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 126, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 127, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 128, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 129, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 130, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 131, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 132, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 133, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 134, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 135, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 136, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 137, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 138, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 139, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 140, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 141, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 142, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 143, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 144, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 145, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 146, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 147, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 148, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 149, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 150, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null }
const livros = [
  { id: 151, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 152, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 153, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 154, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 155, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 156, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 157, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 158, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 159, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null },
  { id: 160, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 161, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 162, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 163, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 164, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 165, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 166, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 167, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 168, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 169, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 170, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 171, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 172, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null },
  { id: 173, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LIMITE", edicao: "", ano: null },
  { id: 174, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA BARREIRA", edicao: "", ano: null },
  { id: 175, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MURO", edicao: "", ano: null },
  { id: 176, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PORTA", edicao: "", ano: null },
  { id: 177, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JANELA", edicao: "", ano: null },
  { id: 178, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SAÍDA", edicao: "", ano: null },
  { id: 179, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENTRADA", edicao: "", ano: null },
  { id: 180, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCOLHA", edicao: "", ano: null },
  { id: 181, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OPÇÃO", edicao: "", ano: null },
  { id: 182, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOTO", edicao: "", ano: null },
  { id: 183, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZ", edicao: "", ano: null },
  { id: 184, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PALAVRA", edicao: "", ano: null },
  { id: 185, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SILÊNCIO", edicao: "", ano: null },
  { id: 186, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GRITO", edicao: "", ano: null },
  { id: 187, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 188, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUIDO", edicao: "", ano: null },
  { id: 189, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 190, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCURIDÃO", edicao: "", ano: null },
  { id: 191, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIA", edicao: "", ano: null },
  { id: 192, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOITE", edicao: "", ano: null },
  { id: 193, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 194, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 195, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 196, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 197, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORÇA", edicao: "", ano: null },
  { id: 198, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 199, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 200, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null }
 const livros = [
  { id: 201, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA INÍCIO", edicao: "", ano: null },
  { id: 202, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIO", edicao: "", ano: null },
  { id: 203, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FIM", edicao: "", ano: null },
  { id: 204, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONTINUIDADE", edicao: "", ano: null },
  { id: 205, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONCLUSÃO", edicao: "", ano: null },
  { id: 206, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESFECHO", edicao: "", ano: null },
  { id: 207, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CLÍMAX", edicao: "", ano: null },
  { id: 208, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENREDO", edicao: "", ano: null },
  { id: 209, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRAMA", edicao: "", ano: null },
  { id: 210, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERSONAGEM", edicao: "", ano: null },
  { id: 211, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROTAGONISTA", edicao: "", ano: null },
  { id: 212, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ANTAGONISTA", edicao: "", ano: null },
  { id: 213, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITO", edicao: "", ano: null },
  { id: 214, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RESOLUÇÃO", edicao: "", ano: null },
  { id: 215, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MISTÉRIO", edicao: "", ano: null },
  { id: 216, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SEGREDO", edicao: "", ano: null },
  { id: 217, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VERDADE", edicao: "", ano: null },
  { id: 218, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTIRA", edicao: "", ano: null },
  { id: 219, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ILUSÃO", edicao: "", ano: null },
  { id: 220, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADE", edicao: "", ano: null },
  { id: 221, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FICÇÃO", edicao: "", ano: null },
  { id: 222, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FANTASIA", edicao: "", ano: null },
  { id: 223, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null },
  { id: 224, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 225, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 226, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 227, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 228, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 229, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 230, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 231, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 232, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 233, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 234, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 235, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 236, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 237, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 238, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 239, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 240, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 241, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 242, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null },
  { id: 243, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TERRA", edicao: "", ano: null },
  { id: 244, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 245, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 246, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 247, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 248, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 249, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 250, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null }
  const livros = [
  { id: 251, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 252, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 253, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 254, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 255, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 256, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 257, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 258, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 259, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 260, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 261, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 262, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 263, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 264, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VONTADE", edicao: "", ano: null },
  { id: 265, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 266, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 267, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 268, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 269, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 270, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 271, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 272, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 273, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 274, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 275, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 276, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 277, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 278, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 279, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 280, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 281, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 282, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 283, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 284, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 285, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 286, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 287, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null },
  { id: 288, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 289, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 290, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 291, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 292, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 293, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 294, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 295, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 296, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 297, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 298, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 299, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 300, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null }
 const livros = [
  { id: 301, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LIMITES", edicao: "", ano: null },
  { id: 302, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA BARREIRAS", edicao: "", ano: null },
  { id: 303, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUROS", edicao: "", ano: null },
  { id: 304, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PORTAS", edicao: "", ano: null },
  { id: 305, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JANELAS", edicao: "", ano: null },
  { id: 306, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SAÍDAS", edicao: "", ano: null },
  { id: 307, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENTRADAS", edicao: "", ano: null },
  { id: 308, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCOLHAS", edicao: "", ano: null },
  { id: 309, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OPÇÕES", edicao: "", ano: null },
  { id: 310, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOTOS", edicao: "", ano: null },
  { id: 311, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZES", edicao: "", ano: null },
  { id: 312, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PALAVRAS", edicao: "", ano: null },
  { id: 313, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SILÊNCIO", edicao: "", ano: null },
  { id: 314, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GRITOS", edicao: "", ano: null },
  { id: 315, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONS", edicao: "", ano: null },
  { id: 316, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUÍDOS", edicao: "", ano: null },
  { id: 317, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZES", edicao: "", ano: null },
  { id: 318, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCURIDÃO", edicao: "", ano: null },
  { id: 319, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIAS", edicao: "", ano: null },
  { id: 320, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOITES", edicao: "", ano: null },
  { id: 321, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPOS", edicao: "", ano: null },
  { id: 322, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇOS", edicao: "", ano: null },
  { id: 323, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIAS", edicao: "", ano: null },
  { id: 324, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIAS", edicao: "", ano: null },
  { id: 325, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORÇAS", edicao: "", ano: null },
  { id: 326, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTOS", edicao: "", ano: null },
  { id: 327, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDAS", edicao: "", ano: null },
  { id: 328, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTES", edicao: "", ano: null },
  { id: 329, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA INÍCIOS", edicao: "", ano: null },
  { id: 330, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIOS", edicao: "", ano: null },
  { id: 331, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FINS", edicao: "", ano: null },
  { id: 332, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONTINUIDADES", edicao: "", ano: null },
  { id: 333, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONCLUSÕES", edicao: "", ano: null },
  { id: 334, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESFECHOS", edicao: "", ano: null },
  { id: 335, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CLÍMAX", edicao: "", ano: null },
  { id: 336, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENREDOS", edicao: "", ano: null },
  { id: 337, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRAMAS", edicao: "", ano: null },
  { id: 338, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERSONAGENS", edicao: "", ano: null },
  { id: 339, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROTAGONISTAS", edicao: "", ano: null },
  { id: 340, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ANTAGONISTAS", edicao: "", ano: null },
  { id: 341, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITOS", edicao: "", ano: null },
  { id: 342, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RESOLUÇÕES", edicao: "", ano: null },
  { id: 343, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MISTÉRIOS", edicao: "", ano: null },
  { id: 344, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SEGREDOS", edicao: "", ano: null },
  { id: 345, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VERDADES", edicao: "", ano: null },
  { id: 346, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTIRAS", edicao: "", ano: null },
  { id: 347, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ILUSÕES", edicao: "", ano: null },
  { id: 348, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADES", edicao: "", ano: null },
  { id: 349, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FICÇÕES", edicao: "", ano: null },
  { id: 350, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FANTASIAS", edicao: "", ano: null }
 const livros = [
  { id: 351, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null },
  { id: 352, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 353, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 354, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 355, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 356, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 357, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 358, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 359, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 360, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 361, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 362, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 363, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 364, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 365, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 366, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 367, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 368, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 369, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 370, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null },
  { id: 371, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TERRA", edicao: "", ano: null },
  { id: 372, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 373, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 374, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 375, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 376, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 377, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 378, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 379, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 380, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 381, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 382, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 383, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 384, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 385, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 386, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 387, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 388, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 389, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 390, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 391, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 392, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 393, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 394, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 395, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 396, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 397, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 398, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 399, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 400, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null }
const livros = [
  { id: 401, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 402, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 403, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 404, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 405, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 406, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 407, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 408, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 409, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 410, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 411, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 412, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 413, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 414, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 415, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 416, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null },
  { id: 417, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 418, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 419, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 420, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 421, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 422, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 423, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 424, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 425, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 426, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 427, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 428, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 429, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 430, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 431, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 432, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 433, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 434, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 435, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 436, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null },
  { id: 437, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 438, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 439, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 440, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 441, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 442, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 443, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 444, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 445, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 446, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 447, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 448, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 449, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null },
  { id: 450, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LIMITES", edicao: "", ano: null }
const livros = [
  { id: 451, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA BARREIRAS", edicao: "", ano: null },
  { id: 452, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUROS", edicao: "", ano: null },
  { id: 453, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PORTAS", edicao: "", ano: null },
  { id: 454, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JANELAS", edicao: "", ano: null },
  { id: 455, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SAÍDAS", edicao: "", ano: null },
  { id: 456, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENTRADAS", edicao: "", ano: null },
  { id: 457, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCOLHAS", edicao: "", ano: null },
  { id: 458, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OPÇÕES", edicao: "", ano: null },
  { id: 459, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOTOS", edicao: "", ano: null },
  { id: 460, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZES", edicao: "", ano: null },
  { id: 461, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PALAVRAS", edicao: "", ano: null },
  { id: 462, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SILÊNCIO", edicao: "", ano: null },
  { id: 463, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GRITOS", edicao: "", ano: null },
  { id: 464, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONS", edicao: "", ano: null },
  { id: 465, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUÍDOS", edicao: "", ano: null },
  { id: 466, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZES", edicao: "", ano: null },
  { id: 467, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCURIDÃO", edicao: "", ano: null },
  { id: 468, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIAS", edicao: "", ano: null },
  { id: 469, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOITES", edicao: "", ano: null },
  { id: 470, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPOS", edicao: "", ano: null },
  { id: 471, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇOS", edicao: "", ano: null },
  { id: 472, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIAS", edicao: "", ano: null },
  { id: 473, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIAS", edicao: "", ano: null },
  { id: 474, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORÇAS", edicao: "", ano: null },
  { id: 475, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTOS", edicao: "", ano: null },
  { id: 476, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDAS", edicao: "", ano: null },
  { id: 477, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTES", edicao: "", ano: null },
  { id: 478, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA INÍCIOS", edicao: "", ano: null },
  { id: 479, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIOS", edicao: "", ano: null },
  { id: 480, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FINS", edicao: "", ano: null },
  { id: 481, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONTINUIDADES", edicao: "", ano: null },
  { id: 482, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONCLUSÕES", edicao: "", ano: null },
  { id: 483, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESFECHOS", edicao: "", ano: null },
  { id: 484, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CLÍMAX", edicao: "", ano: null },
  { id: 485, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENREDOS", edicao: "", ano: null },
  { id: 486, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRAMAS", edicao: "", ano: null },
  { id: 487, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERSONAGENS", edicao: "", ano: null },
  { id: 488, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROTAGONISTAS", edicao: "", ano: null },
  { id: 489, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ANTAGONISTAS", edicao: "", ano: null },
  { id: 490, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITOS", edicao: "", ano: null },
  { id: 491, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RESOLUÇÕES", edicao: "", ano: null },
  { id: 492, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MISTÉRIOS", edicao: "", ano: null },
  { id: 493, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SEGREDOS", edicao: "", ano: null },
  { id: 494, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VERDADES", edicao: "", ano: null },
  { id: 495, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTIRAS", edicao: "", ano: null },
  { id: 496, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ILUSÕES", edicao: "", ano: null },
  { id: 497, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADES", edicao: "", ano: null },
  { id: 498, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FICÇÕES", edicao: "", ano: null },
  { id: 499, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FANTASIAS", edicao: "", ano: null },
  { id: 500, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null }
 const livros = [
  { id: 501, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 502, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 503, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 504, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 505, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 506, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 507, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 508, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 509, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 510, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 511, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 512, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 513, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 514, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 515, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 516, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 517, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 518, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 519, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null },
  { id: 520, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TERRA", edicao: "", ano: null },
  { id: 521, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 522, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 523, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 524, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 525, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 526, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 527, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 528, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 529, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 530, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null }
 const livros = [
  { id: 531, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null },
  { id: 532, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 533, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 534, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 535, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 536, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 537, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 538, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 539, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 540, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 541, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 542, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 543, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 544, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 545, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 546, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 547, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 548, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 549, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 550, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null }
  const livros = [
  { id: 551, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 552, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 553, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 554, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 555, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 556, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 557, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 558, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 559, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 560, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 561, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 562, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 563, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 564, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 565, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 566, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 567, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null },
  { id: 568, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPÍRITO", edicao: "", ano: null },
  { id: 569, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONHOS", edicao: "", ano: null },
  { id: 570, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPERANÇA", edicao: "", ano: null }
  const livros = [
  { id: 571, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FÉ", edicao: "", ano: null },
  { id: 572, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AMOR", edicao: "", ano: null },
  { id: 573, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZ", edicao: "", ano: null },
  { id: 574, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOM", edicao: "", ano: null },
  { id: 575, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA COR", edicao: "", ano: null },
  { id: 576, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORMA", edicao: "", ano: null },
  { id: 577, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUBSTÂNCIA", edicao: "", ano: null },
  { id: 578, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIA", edicao: "", ano: null },
  { id: 579, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIA", edicao: "", ano: null },
  { id: 580, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTO", edicao: "", ano: null },
  { id: 581, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ECO", edicao: "", ano: null },
  { id: 582, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 583, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUMO", edicao: "", ano: null },
  { id: 584, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NORTE", edicao: "", ano: null },
  { id: 585, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SUL", edicao: "", ano: null },
  { id: 586, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LESTE", edicao: "", ano: null },
  { id: 587, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OESTE", edicao: "", ano: null },
  { id: 588, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIREÇÃO", edicao: "", ano: null },
  { id: 589, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GUIA", edicao: "", ano: null },
  { id: 590, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAPA", edicao: "", ano: null }
  const livros = [
  { id: 591, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CAMINHO", edicao: "", ano: null },
  { id: 592, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRADA", edicao: "", ano: null },
  { id: 593, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRILHA", edicao: "", ano: null },
  { id: 594, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO FINAL", edicao: "", ano: null },
  { id: 595, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 596, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RAIZ", edicao: "", ano: null },
  { id: 597, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUGAR", edicao: "", ano: null },
  { id: 598, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CASA", edicao: "", ano: null },
  { id: 599, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TETO", edicao: "", ano: null },
  { id: 600, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null }
 const livros = [
  { id: 601, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA HORIZONTE", edicao: "", ano: null },
  { id: 602, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FRONTEIRA", edicao: "", ano: null },
  { id: 603, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LIMITES", edicao: "", ano: null },
  { id: 604, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA BARREIRAS", edicao: "", ano: null },
  { id: 605, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUROS", edicao: "", ano: null },
  { id: 606, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PORTAS", edicao: "", ano: null },
  { id: 607, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA JANELAS", edicao: "", ano: null },
  { id: 608, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SAÍDAS", edicao: "", ano: null },
  { id: 609, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENTRADAS", edicao: "", ano: null },
  { id: 610, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCOLHAS", edicao: "", ano: null },
  { id: 611, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA OPÇÕES", edicao: "", ano: null },
  { id: 612, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOTOS", edicao: "", ano: null },
  { id: 613, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VOZES", edicao: "", ano: null },
  { id: 614, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PALAVRAS", edicao: "", ano: null },
  { id: 615, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SILÊNCIO", edicao: "", ano: null },
  { id: 616, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GRITOS", edicao: "", ano: null },
  { id: 617, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SONS", edicao: "", ano: null },
  { id: 618, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RUÍDOS", edicao: "", ano: null },
  { id: 619, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUZES", edicao: "", ano: null },
  { id: 620, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESCURIDÃO", edicao: "", ano: null },
  { id: 621, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DIAS", edicao: "", ano: null },
  { id: 622, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOITES", edicao: "", ano: null },
  { id: 623, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPOS", edicao: "", ano: null },
  { id: 624, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇOS", edicao: "", ano: null },
  { id: 625, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MATÉRIAS", edicao: "", ano: null },
  { id: 626, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENERGIAS", edicao: "", ano: null },
  { id: 627, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FORÇAS", edicao: "", ano: null },
  { id: 628, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MOVIMENTOS", edicao: "", ano: null },
  { id: 629, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDAS", edicao: "", ano: null },
  { id: 630, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTES", edicao: "", ano: null },
  { id: 631, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA INÍCIOS", edicao: "", ano: null },
  { id: 632, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MEIOS", edicao: "", ano: null },
  { id: 633, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FINS", edicao: "", ano: null },
  { id: 634, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONTINUIDADES", edicao: "", ano: null },
  { id: 635, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONCLUSÕES", edicao: "", ano: null },
  { id: 636, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESFECHOS", edicao: "", ano: null },
  { id: 637, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CLÍMAX", edicao: "", ano: null },
  { id: 638, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ENREDOS", edicao: "", ano: null },
  { id: 639, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TRAMAS", edicao: "", ano: null },
  { id: 640, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PERSONAGENS", edicao: "", ano: null },
  { id: 641, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROTAGONISTAS", edicao: "", ano: null },
  { id: 642, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ANTAGONISTAS", edicao: "", ano: null },
  { id: 643, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CONFLITOS", edicao: "", ano: null },
  { id: 644, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA RESOLUÇÕES", edicao: "", ano: null },
  { id: 645, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MISTÉRIOS", edicao: "", ano: null },
  { id: 646, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SEGREDOS", edicao: "", ano: null },
  { id: 647, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VERDADES", edicao: "", ano: null },
  { id: 648, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTIRAS", edicao: "", ano: null },
  { id: 649, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ILUSÕES", edicao: "", ano: null },
  { id: 650, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REALIDADES", edicao: "", ano: null }
 const livros = [
  { id: 651, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FICÇÕES", edicao: "", ano: null },
  { id: 652, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FANTASIAS", edicao: "", ano: null },
  { id: 653, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MAGIA", edicao: "", ano: null },
  { id: 654, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CIÊNCIA", edicao: "", ano: null },
  { id: 655, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TECNOLOGIA", edicao: "", ano: null },
  { id: 656, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FUTURO", edicao: "", ano: null },
  { id: 657, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PASSADO", edicao: "", ano: null },
  { id: 658, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PRESENTE", edicao: "", ano: null },
  { id: 659, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TEMPO", edicao: "", ano: null },
  { id: 660, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESPAÇO", edicao: "", ano: null },
  { id: 661, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA UNIVERSO", edicao: "", ano: null },
  { id: 662, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MUNDO", edicao: "", ano: null },
  { id: 663, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PLANETA", edicao: "", ano: null },
  { id: 664, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA GALÁXIA", edicao: "", ano: null },
  { id: 665, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESTRELA", edicao: "", ano: null },
  { id: 666, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOL", edicao: "", ano: null },
  { id: 667, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA LUA", edicao: "", ano: null },
  { id: 668, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CÉU", edicao: "", ano: null },
  { id: 669, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CHÃO", edicao: "", ano: null },
  { id: 670, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA AR", edicao: "", ano: null },
  { id: 671, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ÁGUA", edicao: "", ano: null },
  { id: 672, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA FOGO", edicao: "", ano: null },
  { id: 673, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA TERRA", edicao: "", ano: null },
  { id: 674, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ELEMENTO", edicao: "", ano: null },
  { id: 675, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NATUREZA", edicao: "", ano: null },
  { id: 676, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA VIDA", edicao: "", ano: null },
  { id: 677, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MORTE", edicao: "", ano: null },
  { id: 678, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA DESTINO", edicao: "", ano: null },
  { id: 679, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA PROPÓSITO", edicao: "", ano: null },
  { id: 680, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ESSÊNCIA", edicao: "", ano: null },
  { id: 681, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ORIGEM", edicao: "", ano: null },
  { id: 682, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA IDENTIDADE", edicao: "", ano: null },
  { id: 683, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA NOME", edicao: "", ano: null },
  { id: 684, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ROSTO", edicao: "", ano: null },
  { id: 685, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA SOMBRA", edicao: "", ano: null },
  { id: 686, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA REFLEXO", edicao: "", ano: null },
  { id: 687, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORPO", edicao: "", ano: null },
  { id: 688, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA ALMA", edicao: "", ano: null },
  { id: 689, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA CORAÇÃO", edicao: "", ano: null },
  { id: 690, autor: "KINGS, STEPHEN", titulo: "O HOMEM QUE NÃO TINHA MENTE", edicao: "", ano: null }
  // Continuação na Parte 18...
];
];
];
];
];
];
];
];
];
];
];
];
];
];

function carregarTabela() {
  const corpo = document.getElementById("tabela-livros");
  corpo.innerHTML = "";
  livros.forEach(livro => {
    const linha = `<tr>
      <td>${livro.id}</td>
      <td>${livro.autor}</td>
      <td>${livro.titulo}</td>
      <td>${livro.edicao}</td>
      <td>${livro.ano}</td>
    </tr>`;
    corpo.innerHTML += linha;
  });
}

function filtrarLivros() {
  const termo = document.getElementById("busca").value.toLowerCase();
  const corpo = document.getElementById("tabela-livros");
  corpo.innerHTML = "";
  livros.filter(l =>
    l.autor.toLowerCase().includes(termo) ||
    l.titulo.toLowerCase().includes(termo) ||
    String(l.ano).includes(termo)
  ).forEach(livro => {
    const linha = `<tr>
      <td>${livro.id}</td>
      <td>${livro.autor}</td>
      <td>${livro.titulo}</td>
      <td>${livro.edicao}</td>
      <td>${livro.ano}</td>
    </tr>`;
    corpo.innerHTML += linha;
  });
}

carregarTabela();
